import { useEffect, useRef, useState } from 'react';
import { supabase } from '../../supabaseClient';

interface Karyawan { id:string; id_karyawan:string; nama:string; jabatan?:string; email?:string; gaji_pokok?:number; no_telp?:string; alamat_rumah?:string; }

const isoToday=()=>new Date().toISOString().slice(0,10);
const money=(v:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v||0);

export default function PortalKaryawan(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [user,setUser]=useState<any>(null),[employee,setEmployee]=useState<Karyawan|null>(null),[tab,setTab]=useState<'attendance'|'payslip'>('attendance');
 const [jenis,setJenis]=useState<'Masuk'|'Pulang'>('Masuk'),[photo,setPhoto]=useState<string|null>(null),[location,setLocation]=useState('Mendeteksi GPS…'),[notice,setNotice]=useState('');
 const video=useRef<HTMLVideoElement>(null),canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{supabase.auth.getUser().then(async({data})=>{if(data.user){setUser(data.user);await loadEmployee(data.user.email||'')}});const {data:sub}=supabase.auth.onAuthStateChange((_e,s)=>{if(!s?.user){setUser(null);setEmployee(null)}else{setUser(s.user);loadEmployee(s.user.email||'')}});return()=>sub.subscription.unsubscribe()},[]);
 useEffect(()=>{if(employee&&tab==='attendance'){startCamera();getLocation()}else stopCamera();return stopCamera},[employee,tab]);
 async function loadEmployee(mail:string){const {data,error}=await supabase.from('karyawan').select('*').eq('email',mail).maybeSingle();if(error){setError(error.message);return}if(!data){setError('Akun login belum terhubung ke data karyawan. Hubungi HR untuk mengaktifkan akun.');return}setEmployee(data as Karyawan);setError('')}
 async function login(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');const {data,error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error||!data.user){setError(error?.message||'Login gagal.');setLoading(false);return}await loadEmployee(data.user.email||email);setLoading(false)}
 async function reset(){if(!email)return setError('Masukkan email terlebih dahulu.');setLoading(true);const {error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:window.location.origin});setLoading(false);setNotice(error?error.message:'Link reset password telah dikirim ke email.');}
 async function startCamera(){try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}}});if(video.current){video.current.srcObject=s;await video.current.play()}}catch{setNotice('Kamera tidak tersedia/izin kamera ditolak. Absen tetap dapat dilakukan tanpa foto jika kebijakan perusahaan mengizinkan.')}}
 function stopCamera(){const s=video.current?.srcObject as MediaStream|null;s?.getTracks().forEach(t=>t.stop());if(video.current)video.current.srcObject=null}
 function getLocation(){if(!navigator.geolocation)return setLocation('GPS tidak tersedia');navigator.geolocation.getCurrentPosition(p=>setLocation(`${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)}`),()=>setLocation('Izin GPS ditolak'))}
 function takePhoto(){if(!video.current||!canvas.current)return;const c=canvas.current,v=video.current;c.width=v.videoWidth||640;c.height=v.videoHeight||480;c.getContext('2d')?.drawImage(v,0,0,c.width,c.height);setPhoto(c.toDataURL('image/jpeg',.82))}
 async function attendance(){if(!employee)return;setLoading(true);setNotice('');const date=isoToday();const now=new Date();const time=now.toTimeString().slice(0,5);const {data:existing}=await supabase.from('absensi').select('*').eq('id_karyawan',employee.id_karyawan).eq('tanggal',date).maybeSingle();if(jenis==='Masuk'){if(existing?.jam_masuk){setNotice('Absen masuk hari ini sudah tercatat.');setLoading(false);return}const payload={id_karyawan:employee.id_karyawan,nama:employee.nama,jabatan:employee.jabatan||'',tanggal:date,jam_masuk:time,jam_pulang:null,total_jam:null,status:'Hadir',lokasi:location,selfie_masuk:photo};const {error}=await supabase.from('absensi').insert(payload);setNotice(error?error.message:'Absen masuk berhasil disimpan.')}else{if(!existing){setNotice('Belum ada absen masuk hari ini.');setLoading(false);return}const start=String(existing.jam_masuk||'').split(':').map(Number);const end=time.split(':').map(Number);let mins=(end[0]*60+end[1])-(start[0]*60+start[1]);if(mins<0)mins+=1440;const total=`${Math.floor(mins/60)} Jam ${mins%60} Menit`;const {error}=await supabase.from('absensi').update({jam_pulang:time,total_jam:total,lokasi_pulang:location,selfie_pulang:photo}).eq('id',existing.id);setNotice(error?error.message:`Absen pulang berhasil disimpan. Total: ${total}`)}setPhoto(null);setLoading(false)}
 async function logout(){stopCamera();await supabase.auth.signOut();setEmployee(null);setUser(null)}
 if(!user||!employee)return <div style={box}><h2 style={h2}>👤 Portal Karyawan</h2><p style={muted}>Login menggunakan akun Supabase Auth yang telah diaktifkan HR.</p><form onSubmit={login} style={form}><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required style={input}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required style={input}/>{error&&<div style={err}>{error}</div>}{notice&&<div style={info}>{notice}</div>}<button disabled={loading} style={primary}>{loading?'Memproses…':'Masuk Portal'}</button><button type="button" onClick={reset} style={link}>Lupa password?</button></form><p style={{...muted,fontSize:12,marginTop:18}}>Belum punya akun? Minta HR membuat akun Auth dan memastikan email akun sama dengan email pada data karyawan.</p></div>;
 return <div style={box}><div style={head}><div><h2 style={h2}>Halo, {employee.nama}</h2><p style={muted}>{employee.id_karyawan} · {employee.jabatan||'Karyawan'}</p></div><button onClick={logout} style={danger}>Keluar</button></div><div style={tabs}><button onClick={()=>setTab('attendance')} style={tab==='attendance'?tabOn:tabOff}>Absensi & Selfie</button><button onClick={()=>setTab('payslip')} style={tab==='payslip'?tabOn:tabOff}>Slip Gaji</button></div>{notice&&<div style={info}>{notice}</div>}{tab==='attendance'?<div style={form}><p style={muted}>GPS: <b style={{color:'#fff'}}>{location}</b></p><select value={jenis} onChange={e=>setJenis(e.target.value as any)} style={input}><option>Masuk</option><option>Pulang</option></select><video ref={video} autoPlay playsInline muted style={{width:'100%',maxWidth:420,height:230,objectFit:'cover',borderRadius:12,background:'#000'}}/><canvas ref={canvas} style={{display:'none'}}/><button type="button" onClick={takePhoto} style={secondary}>{photo?'✓ Foto siap':'Ambil Foto Selfie'}</button><button type="button" onClick={attendance} disabled={loading} style={primary}>{loading?'Menyimpan…':`Simpan Absen ${jenis}`}</button></div>:<Payslip employee={employee}/>}</div>
}
function Payslip({employee}:{employee:Karyawan}){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.from('hris_payroll').select('*').eq('id_karyawan',employee.id_karyawan).eq('status','Dibayar').order('periode',{ascending:false}).limit(12).then(({data})=>setRows(data||[]))},[employee.id_karyawan]);return <div>{rows.length?rows.map(r=><div key={r.id} style={card}><b>Periode {r.periode}</b><h3 style={{margin:'10px 0'}}>{money(Number(r.gaji_bersih||0))}</h3><p style={muted}>Status: {r.status} · Dibayar: {r.tanggal_bayar||'-'}</p><button style={secondary} onClick={()=>window.print()}>Cetak Slip</button></div>):<div style={card}>Belum ada slip gaji yang berstatus Dibayar.</div>}</div>}
const box:React.CSSProperties={background:'rgba(20,15,30,.9)',backdropFilter:'blur(14px)',border:'1px solid rgba(255,183,197,.25)',padding:24,borderRadius:16,boxShadow:'0 4px 20px rgba(0,0,0,.5)',color:'#fff',maxWidth:760};
const form:React.CSSProperties={display:'flex',flexDirection:'column',gap:12,maxWidth:430};
const input:React.CSSProperties={padding:11,borderRadius:9,border:'1px solid rgba(255,255,255,.2)',background:'rgba(15,23,42,.85)',color:'#fff'};
const primary:React.CSSProperties={background:'#34d399',color:'#07111f',border:0,padding:11,borderRadius:9,fontWeight:800,cursor:'pointer'};
const secondary:React.CSSProperties={background:'#38bdf8',color:'#07111f',border:0,padding:10,borderRadius:9,fontWeight:800,cursor:'pointer'};
const link:React.CSSProperties={background:'transparent',color:'#38bdf8',border:0,cursor:'pointer',textAlign:'left'};
const danger:React.CSSProperties={background:'#ef4444',color:'#fff',border:0,padding:'8px 12px',borderRadius:8,cursor:'pointer'};
const info:React.CSSProperties={background:'rgba(56,189,248,.12)',border:'1px solid rgba(56,189,248,.25)',padding:10,borderRadius:9,fontSize:12,margin:'10px 0'};
const err:React.CSSProperties={background:'rgba(239,68,68,.12)',border:'1px solid rgba(239,68,68,.3)',padding:10,borderRadius:9,fontSize:12};
const muted:React.CSSProperties={color:'#cbd5e1',fontSize:13,lineHeight:1.5};
const h2:React.CSSProperties={margin:'0 0 6px'};
const head:React.CSSProperties={display:'flex',justifyContent:'space-between',alignItems:'center',gap:20};
const tabs:React.CSSProperties={display:'flex',gap:8,margin:'18px 0'};
const tabOn:React.CSSProperties={...secondary};const tabOff:React.CSSProperties={...secondary,background:'rgba(255,255,255,.1)',color:'#fff'};
const card:React.CSSProperties={background:'rgba(15,23,42,.75)',border:'1px solid rgba(255,255,255,.12)',padding:16,borderRadius:12,marginBottom:10};
